version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: race-results-service-postgres
    environment:
      POSTGRES_DB: race-results-service
      POSTGRES_USER: race-results-service
      POSTGRES_PASSWORD: race-results-service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
